Web/Zerog.Web/Areas/Administration/Controllers/ProductsController.cs
namespace Zerog.Web.Areas.Administration.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Administration.Products;

    [Area("Administration")]
    public class ProductsController : AdministrationController
    {
        private readonly IProductService productService;

        public ProductsController(IProductService productService)
        {
            this.productService = productService;
        }

        public IActionResult Index()
        {
            var products = this.productService.GetAll<ProdunctInfoViewModel>();
            return this.View(products);
        }

        public IActionResult Create()
        {
            var productPartsDto = this.productService.GetProductParts();
            var productParts = new ProductPartsInputModel
            {
                Categories = productPartsDto.Categories,
                Manufacturers = productPartsDto.Manufacturers,
                Specifications = productPartsDto.Specifications,
            };

            var inputModel = new CreateProductInputModel
            {
                ProductParts = productParts,
            };

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateProductInputModel input)
        {
            if (!this.ModelState.IsValid)
            {
                var productPartsDto = this.productService.GetProductParts();
                var productParts = new ProductPartsInputModel
                {
                    Categories = productPartsDto.Categories,
                    Manufacturers = productPartsDto.Manufacturers,
                    Specifications = productPartsDto.Specifications,
                };

                var inputModel = new CreateProductInputModel
                {
                    ProductParts = productParts,
                };

                return this.View(inputModel);
            }

            await this.productService.CreateAsync(input);
            return this.Redirect("/Administration/Products");
        }

        public IActionResult Edit(int id)
        {
            var productPartsDto = this.productService.GetProductParts();
            var productParts = new ProductPartsInputModel
            {
                Categories = productPartsDto.Categories,
                Manufacturers = productPartsDto.Manufacturers,
                Specifications = productPartsDto.Specifications,
            };

            var product = this.productService.GetById(id);

            var inputModel = new CreateProductInputModel
            {
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Discount = product.Discount,
                Category = product.Category,
                Manufacturer = product.Manufacturer,
                Images = product.Images,
                Description = product.Description,
                ProductSpecifications = product.Specificatons,
                ProductParts = productParts,
            };

            return this.View(inputModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, CreateProductInputModel input)
        {
            await this.productService.UpdateAsync(id, input);
            return this.Redirect("/Administration/Products");
        }

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {
            await this.productService.Delete(id);
            return this.Redirect("/Administration/Products");
        }
    }
}

Web/Zerog.Web/Controllers/ProductsController.cs
namespace Zerog.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Products;
    using Zerog.Web.ViewModels.Reviews;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly IReviewService reviewService;

        public ProductsController(IProductService productService, IReviewService reviewService)
        {
            this.productService = productService;
            this.reviewService = reviewService;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var products = this.productService.GetAll<ProductInListViewModel>(id, ItemsPerPage);
            foreach (var product in products)
            {
                product.Stars = this.reviewService.GetAverageStars(product.Id);
            }

            var viewModel = new ProductListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                ProductCount = this.productService.GetCount(),
                Products = products,
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var product = this.productService.GetById(id);

            var viewModel = new SingleProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Discount = product.Discount,
                NewPrice = product.NewPrice,
                Category = product.Category,
                Images = product.Images,
                IsNew = product.IsNew,
                Description = product.Description,
                Manufacturer = product.Manufacturer,
                Specificatons = product.Specificatons,
                Reviews = this.reviewService.GetAll<SingleReviewViewModel>(id),
                Stars = this.reviewService.GetAverageStars(id),
            };

            return this.View(viewModel);
        }
    }
}

Web/Zerog.Web/Controllers/ReviewsController.cs
namespace Zerog.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Reviews;

    public class ReviewsController : BaseController
    {
        private readonly IReviewService reviewService;

        public ReviewsController(IReviewService reviewService)
        {
            this.reviewService = reviewService;
        }

        [Authorize]
        [HttpPost]
        public async Task<IActionResult> Add(CreateReviewInputModel input , int id)
        {
            if (!this.ModelState.IsValid)
            {
                return this.Redirect($"/Reviews/All/{id}");
            }

            input.UserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.reviewService.Add(input);

            return this.Redirect($"/Reviews/All/{id}");
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.reviewService.Remove(userId, id);

            return this.Redirect($"/Reviews/All/{id}");
        }

        [Authorize]
        public IActionResult All(int id)
        {
            var viewModel = new AllReviewsViewModel
            {
                ProductId = id,
                UserId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value,
                Reviews = this.reviewService.GetAll<SingleReviewViewModel>(id),
                AverageStars = this.reviewService.GetAverageStars(id),
                Stars = this.reviewService.GetStarsCount(id),
            };

            return this.View(viewModel);
        }
    }
}

Web/Zerog.Web/Controllers/ShoppingCartsController.cs
namespace Zerog.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Products;
    using Zerog.Web.ViewModels.ShoppingCarts;

    public class ShoppingCartsController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;

        public ShoppingCartsController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        [Authorize]
        public async Task<IActionResult> AddProduct(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.AddProductAsync(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }

        [Authorize]
        public async Task<IActionResult> MyCart()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var cart = await this.shoppingCartService.GetByUserId<ShoppingCartViewModel>(userId);

            return this.View(cart);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.DeleteItem(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }
    }
}

Web/Zerog.Web/Controllers/WishListsController.cs
namespace Zerog.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.WishLists;

    public class WishListsController : BaseController
    {
        private readonly IWishListService wishListService;

        public WishListsController(IWishListService wishListService)
        {
            this.wishListService = wishListService;
        }

        [Authorize]
        public async Task<IActionResult> Add(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.wishListService.AddProductAsync(userId, id);

            return this.Redirect("/WishLists/All");
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.wishListService.RemoveProduct(userId, id);

            return this.Redirect("/WishLists/All");
        }

        [Authorize]
        public IActionResult All()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<WishListViewModel> view = this.wishListService.GetAllProductsAsync<WishListViewModel>(userId).ToList();

            return this.View(view);
        }
    }
}

Web/Zerog.Web/Views/Products/All.cshtml
@model Zerog.Web.ViewModels.Products.ProductListViewModel
@(ViewData["Title"] = "AllProducts")

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">

            <div class="row">
                @foreach (var product in Model.Products)
                {
                    <!-- product -->
                    <div class="col-md-4 col-xs-6">
                        <a asp-action="ById" asp-route-id="@product.Id">
                            <div class="product ">
                                <div class="product-img">
                                    <img src="@product.ImageUrl" alt="">
                                    <div class="product-label">
                                        @if (product.Discount != null)
                                        {
                                            <span class="sale">-@product.Discount%</span>
                                        }
                                        @if (product.IsNew)
                                        {
                                            <span class="new">NEW</span>
                                        }
                                    </div>
                                </div>
                                <div class="product-body">
                                    <p class="product-category">@product.CategoryName</p>
                                    <h3 class="product-name"><a asp-action="ById" asp-route-id="@product.Id">@product.Name</a></h3>
                                    <h4 class="product-price">
                                        $@product.NewPrice.ToString("F")
                                        @if (product.Discount != null)
                                        {
                                            <del class="product-old-price">$@product.Price.ToString("F")</del>
                                        }
                                    </h4>
                                    <div class="product-rating">
                                        @for (int i = 0; i < (int)product.Stars; i++)
                                        {
                                            <i class="fa fa-star"></i>
                                        }
                                        @for (int i = 0; i < 5 - (int)product.Stars; i++)
                                        {
                                            <i class="fa fa-star-o empty"></i>
                                        }
                                    </div>
                                    <div class="product-btns">
                                        <button class="add-to-wishlist"><a asp-controller="WishLists" asp-action="Add" asp-route-id="@product.Id" ><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></a></button>
                                        <button class="add-to-compare"><a asp-controller="Reviews" asp-action="All" asp-route-id="@product.Id" ><i class="fa fa-comment"></i><span class="tooltipp">add review</span></a></button>
                                        <button class="quick-view"><a asp-action="Products" asp-route-id="@product.Id" ><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></a></button>
                                    </div>
                                </div>
                                <div class="add-to-cart">
                                    <form method="post" asp-controller="ShoppingCarts" asp-action="AddProduct" asp-route-id="@product.Id">
                                        <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                                    </form>
                                </div>
                            </div>
                        </a>
                    </div>
                    <!-- /product -->
                }

            </div>
            <!-- /store products -->
            <!-- store bottom filter -->
            <partial name="_PagingPartial" model="@Model" />
            <!-- /store bottom filter -->
        </div>
        <!-- /STORE -->
    </div>
    <!-- /row -->
</div>
<!-- /container -->
</div>
<!-- /SECTION -->
<!-- NEWSLETTER -->
<div id="newsletter" class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <div class="col-md-12">
                <div class="newsletter">
                    <p>Sign Up for the <strong>NEWSLETTER</strong></p>
                    <form>
                        <input class="input" type="email" placeholder="Enter Your Email">
                        <button class="newsletter-btn"><i class="fa fa-envelope"></i> Subscribe</button>
                    </form>
                    <ul class="newsletter-follow">
                        <li>
                            <a href="#"><i class="fa fa-facebook"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-instagram"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-pinterest"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /NEWSLETTER -->

Web/Zerog.Web/Views/Products/ById.cshtml
@model Zerog.Web.ViewModels.Products.SingleProductViewModel
@(ViewData["Title"] = "Product")

<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- Product main img -->
            <div class="col-md-5 col-md-push-2">
                <div id="product-main-img">
                    @foreach (var image in Model.Images)
                    {
                        <div class="product-preview">
                            <img src="@image" alt="">
                        </div>
                    }
                </div>
            </div>
            <!-- /Product main img -->
            <!-- Product thumb imgs -->
            <div class="col-md-2  col-md-pull-5">
                <div id="product-imgs">
                    @foreach (var image in Model.Images)
                    {
                        <div class="product-preview">
                            <img src="@image" alt="">
                        </div>
                    }
                </div>
            </div>
            <!-- /Product thumb imgs -->
            <!-- Product details -->
            <div class="col-md-5">
                <div class="product-details">
                    <h2 class="product-name">@Model.Name</h2>
                    <div>
                        <div class="product-rating">
                            @for (int i = 0; i < (int)Model.Stars; i++)
                            {
                                <i class="fa fa-star"></i>
                            }
                            @for (int i = 0; i < 5 - (int)Model.Stars; i++)
                            {
                                <i class="fa fa-star-o empty"></i>
                            }
                        </div>
                        <a class="review-link" href="/Reviews/All/@Model.Id">@Model.Reviews.Count Review(s) | Add your review</a>
                    </div>
                    <div>
                        <h3 class="product-price">
                            $@Model.NewPrice.ToString("F")
                            @if (Model.Discount != null)
                            {
                                <del class="product-old-price">$@Model.Price.ToString("F")</del>
                            }
                        </h3>
                        @if (Model.IsNew)
                        {
                            <span class="product-available">NEW</span>
                        }
                    </div>
                    <p>
                        @Model.Manufacturer
                    </p>

                    <div class="add-to-cart">
                        <form method="post" asp-controller="ShoppingCarts" asp-action="AddProduct" asp-route-id="@Model.Id">
                            <button class="add-to-cart-btn"><i class="fa fa-shopping-cart"></i> add to cart</button>
                        </form>
                    </div>

                    <ul class="product-btns">
                        <li><a asp-controller="WishLists" asp-action="Add" asp-route-id="@Model.Id" ><i class="fa fa-heart-o"></i> add to wishlist</a></li>
                        <li><a href="#"><i class="fa fa-exchange"></i> add to compare</a></li>
                    </ul>

                    <ul class="product-links">
                        <li>Category:</li>
                        <li><a href="#">@Model.Category</a></li>
                    </ul>

                    <ul class="product-links">
                        <li>Share:</li>
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-envelope"></i></a></li>
                    </ul>

                </div>
            </div>
            <!-- /Product details -->
            <!-- Product tab -->
            <div class="col-md-12">
                <div id="product-tab">
                    <!-- product tab nav -->
                    <ul class="tab-nav">
                        <li class="active"><a data-toggle="tab" href="#tab1">Specifications</a></li>
                        <li><a data-toggle="tab" href="#tab2">Description</a></li>
                        <li><a data-toggle="tab" href="#tab3">Reviews (@Model.Reviews.Count)</a></li>
                    </ul>
                    <!-- /product tab nav -->
                    <!-- product tab content -->
                    <div class="tab-content">
                        <!-- tab1  -->
                        <div id="tab1" class="tab-pane fade in active">
                            <div class="row">
                                <div class="col-md-12">
                                    <table class="table ttable tablesaw tablesaw-stack stripped-rows">
                                        <tbody>
                                            @foreach (var (key, value) in Model.Specificatons)
                                            {
                                                <tr class="">
                                                    <th class="clmn-head" scope="row">@key:</th>
                                                    <td width="1px" class="hrv"></td>
                                                    <td>
                                                        <ul class="">
                                                            @foreach (var item in value)
                                                            {
                                                                <li>@item</li>
                                                            }
                                                        </ul>
                                                    </td>
                                                </tr>
                                            }

                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <!-- /tab1  -->
                        <!-- tab2  -->
                        <div id="tab2" class="tab-pane fade in">
                            <div class="row">
                                <div class="col-md-12">
                                    <p>@Model.Description</p>
                                </div>
                            </div>
                        </div>
                        <!-- /tab2  -->
                        <!-- tab3  -->
                        <div id="tab3" class="tab-pane fade in">
                            <div class="row">
                                <!-- Reviews -->
                                <div class="col-md-5"></div>
                                <div class="col-md-6">
                                    <div id="reviews">
                                        <ul class="reviews">
                                            @foreach (var review in Model.Reviews)
                                            {
                                                <li>
                                                    <div class="review-heading">
                                                        <h5 class="name">@review.UserName</h5>
                                                        <p class="date">@review.Date</p>
                                                        <div class="review-rating">
                                                            @for (int i = 0; i < review.Stars; i++)
                                                            {
                                                                <i class="fa fa-star"></i>
                                                            }
                                                            @for (int i = 0; i < 5 - review.Stars; i++)
                                                            {
                                                                <i class="fa fa-star-o empty"></i>
                                                            }
                                                        </div>
                                                    </div>
                                                    <div class="review-body">
                                                        <p>@review.Content</p>
                                                    </div>
                                                </li>
                                            }
                                        </ul>
                                    </div>
                                </div>
                                <!-- /Reviews -->
                            </div>
                        </div>
                        <!-- /tab3  -->
                    </div>
                    <!-- /product tab content  -->
                </div>
            </div>
            <!-- /product tab -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->

Web/Zerog.Web/Views/Products/Create.cshtml
@model Zerog.Web.ViewModels.Products.CreateProductInputModel

<form method="post" class="col-md-6 " enctype="multipart/form-data">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control input" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Price"></label>
        <input asp-for="Price" class="form-control input" />
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Discount"></label>
        <input asp-for="Discount" class="form-control input" />
        <span asp-validation-for="Discount" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Category"></label>
        <input asp-for="Category" list="categories" class="form-control input" />
        <datalist id="categories">
            @foreach (var category in Model.ProductParts.Categories)
            {
                <option value="@category"> </option>
            }
        </datalist>
        <span asp-validation-for="Category" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Manufacturer"></label>
        <input asp-for="Manufacturer" list="manufacturers" class="form-control input" />
        <datalist id="manufacturers">
            @foreach (var manufacturer in Model.ProductParts.Manufacturers)
            {
                <option value="@manufacturer"> </option>
            }
        </datalist>
        <span asp-validation-for="Manufacturer" class="text-danger"></span>
    </div>

    <div id="ImagesContainer">
        <label asp-for="Images"></label>
        <button class="btn btn-success" type="button" onclick="addInput(this,'Images')">Add</button>
        <div class="form-group">
            <input type="text" name="Images[0]" class="form-control input">
            <span asp-validation-for="Images" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="form-control input"></textarea>
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>

    <div id="PortsContainer" class="form-group">
        <label asp-for="ProductSpecifications"></label>
        <div class="form-inline form-group">
            <input asp-for="ProductSpecifications" list="specificationNames" class="form-control input" />
            <button class="btn btn-success" type="button" onclick="addSpecificationName(this)">AddSpecification</button>
        </div>
        <datalist id="specificationNames">
            @foreach (var key in Model.ProductParts.Specifications.Keys)
            {
                <option value="@key"> </option>
            }
        </datalist>
    </div>

    <input type="submit" class="btn btn-primary" value="Create" />
</form>

@section Scripts{

    <script>
        function addInput(x, PropName) {
            var parentNode = x.parentNode;
            var div = parentNode.children[2].cloneNode(true);
            var count = parentNode.children.length - 2;
            div.children[0].value = "";
            div.children[0].setAttribute("name", PropName + "[" + count + "]");
            parentNode.appendChild(div);
        };
    </script>
    <script>
        function addSpecificationName(x) {
            var parentNode = x.parentNode;
            var value = parentNode.children[0].value;
            if (value == "") {
                return 0;
            }

            var div = document.createElement("div");
            div.classList.add("form-group");

            var label = document.createElement("label");
            label.innerText = value;
            div.appendChild(label);

            var button = document.createElement("button");
            button.classList.add("btn");
            button.classList.add("btn-success");
            button.setAttribute("type", "button");
            button.innerHTML = "+";
            button.setAttribute("onclick", "addMore(this)");
            div.appendChild(button);

            var input = document.createElement("input");
            input.classList.add("form-group");
            input.classList.add("input");
            input.setAttribute("name", "ProductSpecifications[" + value + "][0]")
            div.appendChild(input);

            parentNode.parentNode.appendChild(div);
            parentNode.children[0].value = "";
        };
    </script>

    <script>
        function addMore(x) {
            var parentNode = x.parentNode;
            var index = parentNode.children.length - 2;
            var value = parentNode.children[0].innerText;

            var input = document.createElement("input");
            input.classList.add("form-group");
            input.classList.add("input");
            input.setAttribute("name", "ProductSpecifications[" + value + "][" + index + "]")

            parentNode.appendChild(input);
        };
    </script>
}