Web/Zerog.Web/Controllers/ProductsController.cs
namespace Zerog.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Products;
    using Zerog.Web.ViewModels.Reviews;

    public class ProductsController : BaseController
    {
        private readonly IProductService productService;
        private readonly IReviewService reviewService;

        public ProductsController(IProductService productService, IReviewService reviewService)
        {
            this.productService = productService;
            this.reviewService = reviewService;
        }

        public IActionResult All(int id = 1)
        {
            if (id <= 0)
            {
                return this.NotFound();
            }

            const int ItemsPerPage = 12;
            var products = this.productService.GetAll<ProductInListViewModel>(id, ItemsPerPage);
            foreach (var product in products)
            {
                product.Stars = this.reviewService.GetAverageStars(product.Id);
            }

            var viewModel = new ProductListViewModel
            {
                ItemsPerPage = ItemsPerPage,
                PageNumber = id,
                ProductCount = this.productService.GetCount(),
                Products = products,
            };

            return this.View(viewModel);
        }

        public IActionResult ById(int id)
        {
            var product = this.productService.GetById(id);

            var viewModel = new SingleProductViewModel
            {
                Id = product.Id,
                Name = product.Name,
                Price = product.Price,
                Discount = product.Discount,
                NewPrice = product.NewPrice,
                Category = product.Category,
                Images = product.Images,
                IsNew = product.IsNew,
                Description = product.Description,
                Manufacturer = product.Manufacturer,
                Specificatons = product.Specificatons,
                Reviews = this.reviewService.GetAll<SingleReviewViewModel>(id),
                Stars = this.reviewService.GetAverageStars(id),
            };

            return this.View(viewModel);
        }
    }
}

Web/Zerog.Web/Controllers/ShoppingCartsController.cs
namespace Zerog.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Products;
    using Zerog.Web.ViewModels.ShoppingCarts;

    public class ShoppingCartsController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;

        public ShoppingCartsController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        [Authorize]
        public async Task<IActionResult> AddProduct(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.AddProductAsync(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }

        [Authorize]
        public async Task<IActionResult> MyCart()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var cart = await this.shoppingCartService.GetByUserId<ShoppingCartViewModel>(userId);

            return this.View(cart);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.DeleteItem(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }
    }
}

Web/Zerog.Web/Controllers/WishListsController.cs
namespace Zerog.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.WishLists;

    public class WishListsController : BaseController
    {
        private readonly IWishListService wishListService;

        public WishListsController(IWishListService wishListService)
        {
            this.wishListService = wishListService;
        }

        [Authorize]
        public async Task<IActionResult> Add(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.wishListService.AddProductAsync(userId, id);

            return this.Redirect("/WishLists/All");
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.wishListService.RemoveProduct(userId, id);

            return this.Redirect("/WishLists/All");
        }

        [Authorize]
        public IActionResult All()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            List<WishListViewModel> view = this.wishListService.GetAllProductsAsync<WishListViewModel>(userId).ToList();

            return this.View(view);
        }
    }
}

Web/Zerog.Web/Views/WishLists/All.cshtml
@model List<Zerog.Web.ViewModels.WishLists.WishListViewModel>
@(ViewData["Title"] = "MyWishList")

<table class="table">
    <thead>
        <tr>
            <th><span>Product</span></th>
            <th><span>Price</span></th>
            <th><span>Category</span></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img src="@item.ImageUrl" alt="" width="50" height="40">
                    <a asp-controller="Products" asp-action="ById" asp-route-id="@item.Id">@item.Name</a>
                </td>
                <td>
                    $@item.NewPrice
                </td>
                <td>
                    @item.CategoryName
                </td>
                <td>
                    <a asp-controller="Products" asp-action="ById" asp-route-id="@item.Id" class="table-link">
                        <span class="fa-stack">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-search-plus fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    <a asp-controller="ShoppingCarts" asp-action="AddProduct" asp-route-id="@item.Id" class="table-link">
                        <span class="fa-stack">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa  fa-shopping-cart fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="table-link danger">
                        <span class="fa-stack">
                            <i class="fa fa-square fa-stack-2x"></i>
                            <i class="fa fa-trash-o fa-stack-1x fa-inverse"></i>
                        </span>
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>