Web/Zerog.Web/Controllers/OrdersController.cs
namespace Zerog.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Orders;

    public class OrdersController : BaseController
    {
        private readonly IOrdersService orderService;
        private readonly IShoppingCartService shoppingCartService;
        private readonly IAddressService addressService;

        public OrdersController(
            IOrdersService orderService,
            IShoppingCartService shoppingCartService,
            IAddressService addressService)
        {
            this.orderService = orderService;
            this.shoppingCartService = shoppingCartService;
            this.addressService = addressService;
        }

        [Authorize]
        public async Task<IActionResult> Create(string payment)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var haveAddress = this.addressService.UserHavaAddress(userId);
            if (!haveAddress)
            {
                return this.Redirect("/Addresses/Create");
            }

            await this.orderService.Add(userId, payment);

            await this.shoppingCartService.ClearItems(userId);

            return this.Redirect("/Orders/MyOrders");
        }


        [Authorize]
        public IActionResult MyOrders()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var viewModel = this.orderService.GetAllOrdersById(userId);

            return this.View(viewModel);
        }

        [Authorize]
        public IActionResult ById(int id)
        {
            var items = this.orderService.GetOrderProductListById(id);

            var userName = this.User.FindFirst(ClaimTypes.Name).Value;
            var email = this.User.FindFirst(ClaimTypes.Email).Value;
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
            var address = this.addressService.GetByUserId(userId);
            var order = this.orderService.GetOrderById(id);

            var viewModel = new OrderViewModel
            {
                FullName = $"{address.FirstName} {address.LastName}",
                Username = userName,
                Email = email,
                Date = order.Date,
                Phone = address.PhoneNumber,
                Country = $"{address.Country}, {address.ZipCode}",
                City = address.City,
                Address = address.Addreess,
                Items = items,
                PaymentMethod = order.PaymentMethod,
                Status = order.Status,
                Total = order.Total,
            };

            return this.View(viewModel);
        }
    }
}

Web/Zerog.Web/Controllers/ShoppingCartsController.cs
namespace Zerog.Web.Controllers
{
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using Zerog.Services.Data;
    using Zerog.Web.ViewModels.Products;
    using Zerog.Web.ViewModels.ShoppingCarts;

    public class ShoppingCartsController : BaseController
    {
        private readonly IShoppingCartService shoppingCartService;

        public ShoppingCartsController(IShoppingCartService shoppingCartService)
        {
            this.shoppingCartService = shoppingCartService;
        }

        [Authorize]
        public async Task<IActionResult> AddProduct(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.AddProductAsync(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }

        [Authorize]
        public async Task<IActionResult> MyCart()
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            var cart = await this.shoppingCartService.GetByUserId<ShoppingCartViewModel>(userId);

            return this.View(cart);
        }

        [Authorize]
        public async Task<IActionResult> Delete(int id)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.shoppingCartService.DeleteItem(userId, id);

            return this.Redirect("/ShoppingCarts/MyCart");
        }
    }
}

Web/Zerog.Web/Views/ShoppingCarts/MyCart.cshtml
@model Zerog.Web.ViewModels.ShoppingCarts.ShoppingCartViewModel
@(ViewData["Title"] = "MyShoppingCart")

<!-- SECTION -->
<div class="section">
    <!-- container -->
    <div class="container">
        <!-- row -->
        <div class="row">
            <!-- Order Details -->
            <div class="col-md-5 order-details">
                <div class="section-title text-center">
                    <h3 class="title">Your Order</h3>
                </div>
                <div class="order-summary">
                    <div class="order-col">
                        <div><strong>PRODUCT</strong></div>
                        <div><strong>PRICE</strong></div>
                    </div>
                    <div class="order-products">
                        @foreach (var item in Model.Items)
                        {
                            <div class="order-col">
                                <a class="btn btn-primary btn-warning" asp-action="Delete" asp-route-id="@item.Id">-</a>
                                <div>@item.Quantity x @item.ProductName</div>
                                <div>$@item.ProductNewPrice.ToString("F")</div>
                            </div>
                        }
                    </div>
                    <div class="order-col">
                        <div>Shiping</div>
                        <div><strong>FREE</strong></div>
                    </div>
                    <div class="order-col">
                        <div><strong>TOTAL</strong></div>
                        <div><strong class="order-total">$@Model.Total.ToString("F")</strong></div>
                    </div>
                </div>
                <form class="payment-method" method="post" asp-controller="Orders" asp-action="Create" >
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-1" value="Direct Bank Transfer">
                        <label for="payment-1">
                            <span></span>
                            Direct Bank Transfer
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-2" value="Cheque Payment">
                        <label for="payment-2">
                            <span></span>
                            Cheque Payment
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-radio">
                        <input type="radio" name="payment" id="payment-3" value="Paypal System">
                        <label for="payment-3">
                            <span></span>
                            Paypal System
                        </label>
                        <div class="caption">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="input-checkbox">
                        <input type="checkbox" id="terms">
                        <label for="terms">
                            <span></span>
                            I've read and accept the <a href="#">terms & conditions</a>
                        </label>
                    </div>

                    <button class="primary-btn order-submit">Place order</button>
                </form>
            </div>
            <!-- /Order Details -->
        </div>
        <!-- /row -->
    </div>
    <!-- /container -->
</div>
<!-- /SECTION -->